/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

syntax = "proto3";
package service.v1;

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "metrics/v1/metrics.proto";

service Monitord {
  rpc Report(google.protobuf.Empty) returns (stream ReportPayload);
}

message ReportPayload {
    bytes data = 1;
}

message ReportResponse {
  google.protobuf.Timestamp timestamp = 1;
  metrics.v1.Snapshot report = 2;
}
